services:
  - type: web
    name: energy-water-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:10000 app:app
    plan: free  # Use Render's free tier
    autoDeploy: true